// source: yeying/api/web3/web3.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.yeying.api.web3.BlockAddress', null, global);
goog.exportSymbol('proto.yeying.api.web3.Identity', null, global);
goog.exportSymbol('proto.yeying.api.web3.Identity.ExtendCase', null, global);
goog.exportSymbol('proto.yeying.api.web3.IdentityApplicationExtend', null, global);
goog.exportSymbol('proto.yeying.api.web3.IdentityCodeEnum', null, global);
goog.exportSymbol('proto.yeying.api.web3.IdentityMetadata', null, global);
goog.exportSymbol('proto.yeying.api.web3.IdentityOrganizationExtend', null, global);
goog.exportSymbol('proto.yeying.api.web3.IdentityPersonalExtend', null, global);
goog.exportSymbol('proto.yeying.api.web3.IdentityServiceExtend', null, global);
goog.exportSymbol('proto.yeying.api.web3.Mnemonic', null, global);
goog.exportSymbol('proto.yeying.api.web3.NetworkTypeEnum', null, global);
goog.exportSymbol('proto.yeying.api.web3.SecurityAlgorithm', null, global);
goog.exportSymbol('proto.yeying.api.web3.SecurityConfig', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yeying.api.web3.Identity = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.yeying.api.web3.Identity.oneofGroups_);
};
goog.inherits(proto.yeying.api.web3.Identity, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yeying.api.web3.Identity.displayName = 'proto.yeying.api.web3.Identity';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yeying.api.web3.IdentityMetadata = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yeying.api.web3.IdentityMetadata, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yeying.api.web3.IdentityMetadata.displayName = 'proto.yeying.api.web3.IdentityMetadata';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yeying.api.web3.BlockAddress = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yeying.api.web3.BlockAddress, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yeying.api.web3.BlockAddress.displayName = 'proto.yeying.api.web3.BlockAddress';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yeying.api.web3.Mnemonic = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yeying.api.web3.Mnemonic, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yeying.api.web3.Mnemonic.displayName = 'proto.yeying.api.web3.Mnemonic';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yeying.api.web3.IdentityServiceExtend = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yeying.api.web3.IdentityServiceExtend, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yeying.api.web3.IdentityServiceExtend.displayName = 'proto.yeying.api.web3.IdentityServiceExtend';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yeying.api.web3.IdentityOrganizationExtend = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yeying.api.web3.IdentityOrganizationExtend, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yeying.api.web3.IdentityOrganizationExtend.displayName = 'proto.yeying.api.web3.IdentityOrganizationExtend';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yeying.api.web3.IdentityPersonalExtend = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yeying.api.web3.IdentityPersonalExtend, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yeying.api.web3.IdentityPersonalExtend.displayName = 'proto.yeying.api.web3.IdentityPersonalExtend';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yeying.api.web3.IdentityApplicationExtend = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.yeying.api.web3.IdentityApplicationExtend.repeatedFields_, null);
};
goog.inherits(proto.yeying.api.web3.IdentityApplicationExtend, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yeying.api.web3.IdentityApplicationExtend.displayName = 'proto.yeying.api.web3.IdentityApplicationExtend';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yeying.api.web3.SecurityConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yeying.api.web3.SecurityConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yeying.api.web3.SecurityConfig.displayName = 'proto.yeying.api.web3.SecurityConfig';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yeying.api.web3.SecurityAlgorithm = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yeying.api.web3.SecurityAlgorithm, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yeying.api.web3.SecurityAlgorithm.displayName = 'proto.yeying.api.web3.SecurityAlgorithm';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.yeying.api.web3.Identity.oneofGroups_ = [[4,5,6,7]];

/**
 * @enum {number}
 */
proto.yeying.api.web3.Identity.ExtendCase = {
  EXTEND_NOT_SET: 0,
  PERSONALEXTEND: 4,
  SERVICEEXTEND: 5,
  ORGANIZATIONEXTEND: 6,
  APPLICATIONEXTEND: 7
};

/**
 * @return {proto.yeying.api.web3.Identity.ExtendCase}
 */
proto.yeying.api.web3.Identity.prototype.getExtendCase = function() {
  return /** @type {proto.yeying.api.web3.Identity.ExtendCase} */(jspb.Message.computeOneofCase(this, proto.yeying.api.web3.Identity.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yeying.api.web3.Identity.prototype.toObject = function(opt_includeInstance) {
  return proto.yeying.api.web3.Identity.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yeying.api.web3.Identity} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yeying.api.web3.Identity.toObject = function(includeInstance, msg) {
  var f, obj = {
    metadata: (f = msg.getMetadata()) && proto.yeying.api.web3.IdentityMetadata.toObject(includeInstance, f),
    blockaddress: jspb.Message.getFieldWithDefault(msg, 2, ""),
    securityconfig: (f = msg.getSecurityconfig()) && proto.yeying.api.web3.SecurityConfig.toObject(includeInstance, f),
    personalextend: (f = msg.getPersonalextend()) && proto.yeying.api.web3.IdentityPersonalExtend.toObject(includeInstance, f),
    serviceextend: (f = msg.getServiceextend()) && proto.yeying.api.web3.IdentityServiceExtend.toObject(includeInstance, f),
    organizationextend: (f = msg.getOrganizationextend()) && proto.yeying.api.web3.IdentityOrganizationExtend.toObject(includeInstance, f),
    applicationextend: (f = msg.getApplicationextend()) && proto.yeying.api.web3.IdentityApplicationExtend.toObject(includeInstance, f),
    signature: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yeying.api.web3.Identity}
 */
proto.yeying.api.web3.Identity.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yeying.api.web3.Identity;
  return proto.yeying.api.web3.Identity.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yeying.api.web3.Identity} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yeying.api.web3.Identity}
 */
proto.yeying.api.web3.Identity.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.yeying.api.web3.IdentityMetadata;
      reader.readMessage(value,proto.yeying.api.web3.IdentityMetadata.deserializeBinaryFromReader);
      msg.setMetadata(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBlockaddress(value);
      break;
    case 3:
      var value = new proto.yeying.api.web3.SecurityConfig;
      reader.readMessage(value,proto.yeying.api.web3.SecurityConfig.deserializeBinaryFromReader);
      msg.setSecurityconfig(value);
      break;
    case 4:
      var value = new proto.yeying.api.web3.IdentityPersonalExtend;
      reader.readMessage(value,proto.yeying.api.web3.IdentityPersonalExtend.deserializeBinaryFromReader);
      msg.setPersonalextend(value);
      break;
    case 5:
      var value = new proto.yeying.api.web3.IdentityServiceExtend;
      reader.readMessage(value,proto.yeying.api.web3.IdentityServiceExtend.deserializeBinaryFromReader);
      msg.setServiceextend(value);
      break;
    case 6:
      var value = new proto.yeying.api.web3.IdentityOrganizationExtend;
      reader.readMessage(value,proto.yeying.api.web3.IdentityOrganizationExtend.deserializeBinaryFromReader);
      msg.setOrganizationextend(value);
      break;
    case 7:
      var value = new proto.yeying.api.web3.IdentityApplicationExtend;
      reader.readMessage(value,proto.yeying.api.web3.IdentityApplicationExtend.deserializeBinaryFromReader);
      msg.setApplicationextend(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setSignature(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yeying.api.web3.Identity.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yeying.api.web3.Identity.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yeying.api.web3.Identity} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yeying.api.web3.Identity.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMetadata();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.yeying.api.web3.IdentityMetadata.serializeBinaryToWriter
    );
  }
  f = message.getBlockaddress();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSecurityconfig();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.yeying.api.web3.SecurityConfig.serializeBinaryToWriter
    );
  }
  f = message.getPersonalextend();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.yeying.api.web3.IdentityPersonalExtend.serializeBinaryToWriter
    );
  }
  f = message.getServiceextend();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.yeying.api.web3.IdentityServiceExtend.serializeBinaryToWriter
    );
  }
  f = message.getOrganizationextend();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.yeying.api.web3.IdentityOrganizationExtend.serializeBinaryToWriter
    );
  }
  f = message.getApplicationextend();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.yeying.api.web3.IdentityApplicationExtend.serializeBinaryToWriter
    );
  }
  f = message.getSignature();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
};


/**
 * optional IdentityMetadata metadata = 1;
 * @return {?proto.yeying.api.web3.IdentityMetadata}
 */
proto.yeying.api.web3.Identity.prototype.getMetadata = function() {
  return /** @type{?proto.yeying.api.web3.IdentityMetadata} */ (
    jspb.Message.getWrapperField(this, proto.yeying.api.web3.IdentityMetadata, 1));
};


/**
 * @param {?proto.yeying.api.web3.IdentityMetadata|undefined} value
 * @return {!proto.yeying.api.web3.Identity} returns this
*/
proto.yeying.api.web3.Identity.prototype.setMetadata = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yeying.api.web3.Identity} returns this
 */
proto.yeying.api.web3.Identity.prototype.clearMetadata = function() {
  return this.setMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yeying.api.web3.Identity.prototype.hasMetadata = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string blockAddress = 2;
 * @return {string}
 */
proto.yeying.api.web3.Identity.prototype.getBlockaddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.Identity} returns this
 */
proto.yeying.api.web3.Identity.prototype.setBlockaddress = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional SecurityConfig securityConfig = 3;
 * @return {?proto.yeying.api.web3.SecurityConfig}
 */
proto.yeying.api.web3.Identity.prototype.getSecurityconfig = function() {
  return /** @type{?proto.yeying.api.web3.SecurityConfig} */ (
    jspb.Message.getWrapperField(this, proto.yeying.api.web3.SecurityConfig, 3));
};


/**
 * @param {?proto.yeying.api.web3.SecurityConfig|undefined} value
 * @return {!proto.yeying.api.web3.Identity} returns this
*/
proto.yeying.api.web3.Identity.prototype.setSecurityconfig = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yeying.api.web3.Identity} returns this
 */
proto.yeying.api.web3.Identity.prototype.clearSecurityconfig = function() {
  return this.setSecurityconfig(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yeying.api.web3.Identity.prototype.hasSecurityconfig = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional IdentityPersonalExtend personalExtend = 4;
 * @return {?proto.yeying.api.web3.IdentityPersonalExtend}
 */
proto.yeying.api.web3.Identity.prototype.getPersonalextend = function() {
  return /** @type{?proto.yeying.api.web3.IdentityPersonalExtend} */ (
    jspb.Message.getWrapperField(this, proto.yeying.api.web3.IdentityPersonalExtend, 4));
};


/**
 * @param {?proto.yeying.api.web3.IdentityPersonalExtend|undefined} value
 * @return {!proto.yeying.api.web3.Identity} returns this
*/
proto.yeying.api.web3.Identity.prototype.setPersonalextend = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.yeying.api.web3.Identity.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yeying.api.web3.Identity} returns this
 */
proto.yeying.api.web3.Identity.prototype.clearPersonalextend = function() {
  return this.setPersonalextend(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yeying.api.web3.Identity.prototype.hasPersonalextend = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional IdentityServiceExtend serviceExtend = 5;
 * @return {?proto.yeying.api.web3.IdentityServiceExtend}
 */
proto.yeying.api.web3.Identity.prototype.getServiceextend = function() {
  return /** @type{?proto.yeying.api.web3.IdentityServiceExtend} */ (
    jspb.Message.getWrapperField(this, proto.yeying.api.web3.IdentityServiceExtend, 5));
};


/**
 * @param {?proto.yeying.api.web3.IdentityServiceExtend|undefined} value
 * @return {!proto.yeying.api.web3.Identity} returns this
*/
proto.yeying.api.web3.Identity.prototype.setServiceextend = function(value) {
  return jspb.Message.setOneofWrapperField(this, 5, proto.yeying.api.web3.Identity.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yeying.api.web3.Identity} returns this
 */
proto.yeying.api.web3.Identity.prototype.clearServiceextend = function() {
  return this.setServiceextend(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yeying.api.web3.Identity.prototype.hasServiceextend = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional IdentityOrganizationExtend organizationExtend = 6;
 * @return {?proto.yeying.api.web3.IdentityOrganizationExtend}
 */
proto.yeying.api.web3.Identity.prototype.getOrganizationextend = function() {
  return /** @type{?proto.yeying.api.web3.IdentityOrganizationExtend} */ (
    jspb.Message.getWrapperField(this, proto.yeying.api.web3.IdentityOrganizationExtend, 6));
};


/**
 * @param {?proto.yeying.api.web3.IdentityOrganizationExtend|undefined} value
 * @return {!proto.yeying.api.web3.Identity} returns this
*/
proto.yeying.api.web3.Identity.prototype.setOrganizationextend = function(value) {
  return jspb.Message.setOneofWrapperField(this, 6, proto.yeying.api.web3.Identity.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yeying.api.web3.Identity} returns this
 */
proto.yeying.api.web3.Identity.prototype.clearOrganizationextend = function() {
  return this.setOrganizationextend(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yeying.api.web3.Identity.prototype.hasOrganizationextend = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional IdentityApplicationExtend applicationExtend = 7;
 * @return {?proto.yeying.api.web3.IdentityApplicationExtend}
 */
proto.yeying.api.web3.Identity.prototype.getApplicationextend = function() {
  return /** @type{?proto.yeying.api.web3.IdentityApplicationExtend} */ (
    jspb.Message.getWrapperField(this, proto.yeying.api.web3.IdentityApplicationExtend, 7));
};


/**
 * @param {?proto.yeying.api.web3.IdentityApplicationExtend|undefined} value
 * @return {!proto.yeying.api.web3.Identity} returns this
*/
proto.yeying.api.web3.Identity.prototype.setApplicationextend = function(value) {
  return jspb.Message.setOneofWrapperField(this, 7, proto.yeying.api.web3.Identity.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yeying.api.web3.Identity} returns this
 */
proto.yeying.api.web3.Identity.prototype.clearApplicationextend = function() {
  return this.setApplicationextend(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yeying.api.web3.Identity.prototype.hasApplicationextend = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional string signature = 8;
 * @return {string}
 */
proto.yeying.api.web3.Identity.prototype.getSignature = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.Identity} returns this
 */
proto.yeying.api.web3.Identity.prototype.setSignature = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yeying.api.web3.IdentityMetadata.prototype.toObject = function(opt_includeInstance) {
  return proto.yeying.api.web3.IdentityMetadata.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yeying.api.web3.IdentityMetadata} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yeying.api.web3.IdentityMetadata.toObject = function(includeInstance, msg) {
  var f, obj = {
    parent: jspb.Message.getFieldWithDefault(msg, 1, ""),
    network: jspb.Message.getFieldWithDefault(msg, 2, 0),
    did: jspb.Message.getFieldWithDefault(msg, 3, ""),
    version: jspb.Message.getFieldWithDefault(msg, 4, 0),
    address: jspb.Message.getFieldWithDefault(msg, 5, ""),
    name: jspb.Message.getFieldWithDefault(msg, 6, ""),
    description: jspb.Message.getFieldWithDefault(msg, 7, ""),
    code: jspb.Message.getFieldWithDefault(msg, 8, 0),
    avatar: jspb.Message.getFieldWithDefault(msg, 9, ""),
    created: jspb.Message.getFieldWithDefault(msg, 10, ""),
    checkpoint: jspb.Message.getFieldWithDefault(msg, 11, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yeying.api.web3.IdentityMetadata}
 */
proto.yeying.api.web3.IdentityMetadata.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yeying.api.web3.IdentityMetadata;
  return proto.yeying.api.web3.IdentityMetadata.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yeying.api.web3.IdentityMetadata} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yeying.api.web3.IdentityMetadata}
 */
proto.yeying.api.web3.IdentityMetadata.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setParent(value);
      break;
    case 2:
      var value = /** @type {!proto.yeying.api.web3.NetworkTypeEnum} */ (reader.readEnum());
      msg.setNetwork(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDid(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setVersion(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddress(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 8:
      var value = /** @type {!proto.yeying.api.web3.IdentityCodeEnum} */ (reader.readEnum());
      msg.setCode(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setAvatar(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreated(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setCheckpoint(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yeying.api.web3.IdentityMetadata.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yeying.api.web3.IdentityMetadata.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yeying.api.web3.IdentityMetadata} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yeying.api.web3.IdentityMetadata.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getParent();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNetwork();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getDid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getVersion();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getAddress();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getCode();
  if (f !== 0.0) {
    writer.writeEnum(
      8,
      f
    );
  }
  f = message.getAvatar();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getCreated();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getCheckpoint();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
};


/**
 * optional string parent = 1;
 * @return {string}
 */
proto.yeying.api.web3.IdentityMetadata.prototype.getParent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.IdentityMetadata} returns this
 */
proto.yeying.api.web3.IdentityMetadata.prototype.setParent = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional NetworkTypeEnum network = 2;
 * @return {!proto.yeying.api.web3.NetworkTypeEnum}
 */
proto.yeying.api.web3.IdentityMetadata.prototype.getNetwork = function() {
  return /** @type {!proto.yeying.api.web3.NetworkTypeEnum} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.yeying.api.web3.NetworkTypeEnum} value
 * @return {!proto.yeying.api.web3.IdentityMetadata} returns this
 */
proto.yeying.api.web3.IdentityMetadata.prototype.setNetwork = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string did = 3;
 * @return {string}
 */
proto.yeying.api.web3.IdentityMetadata.prototype.getDid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.IdentityMetadata} returns this
 */
proto.yeying.api.web3.IdentityMetadata.prototype.setDid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional uint32 version = 4;
 * @return {number}
 */
proto.yeying.api.web3.IdentityMetadata.prototype.getVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.yeying.api.web3.IdentityMetadata} returns this
 */
proto.yeying.api.web3.IdentityMetadata.prototype.setVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string address = 5;
 * @return {string}
 */
proto.yeying.api.web3.IdentityMetadata.prototype.getAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.IdentityMetadata} returns this
 */
proto.yeying.api.web3.IdentityMetadata.prototype.setAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string name = 6;
 * @return {string}
 */
proto.yeying.api.web3.IdentityMetadata.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.IdentityMetadata} returns this
 */
proto.yeying.api.web3.IdentityMetadata.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string description = 7;
 * @return {string}
 */
proto.yeying.api.web3.IdentityMetadata.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.IdentityMetadata} returns this
 */
proto.yeying.api.web3.IdentityMetadata.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional IdentityCodeEnum code = 8;
 * @return {!proto.yeying.api.web3.IdentityCodeEnum}
 */
proto.yeying.api.web3.IdentityMetadata.prototype.getCode = function() {
  return /** @type {!proto.yeying.api.web3.IdentityCodeEnum} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {!proto.yeying.api.web3.IdentityCodeEnum} value
 * @return {!proto.yeying.api.web3.IdentityMetadata} returns this
 */
proto.yeying.api.web3.IdentityMetadata.prototype.setCode = function(value) {
  return jspb.Message.setProto3EnumField(this, 8, value);
};


/**
 * optional string avatar = 9;
 * @return {string}
 */
proto.yeying.api.web3.IdentityMetadata.prototype.getAvatar = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.IdentityMetadata} returns this
 */
proto.yeying.api.web3.IdentityMetadata.prototype.setAvatar = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string created = 10;
 * @return {string}
 */
proto.yeying.api.web3.IdentityMetadata.prototype.getCreated = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.IdentityMetadata} returns this
 */
proto.yeying.api.web3.IdentityMetadata.prototype.setCreated = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string checkpoint = 11;
 * @return {string}
 */
proto.yeying.api.web3.IdentityMetadata.prototype.getCheckpoint = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.IdentityMetadata} returns this
 */
proto.yeying.api.web3.IdentityMetadata.prototype.setCheckpoint = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yeying.api.web3.BlockAddress.prototype.toObject = function(opt_includeInstance) {
  return proto.yeying.api.web3.BlockAddress.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yeying.api.web3.BlockAddress} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yeying.api.web3.BlockAddress.toObject = function(includeInstance, msg) {
  var f, obj = {
    identifier: jspb.Message.getFieldWithDefault(msg, 1, ""),
    address: jspb.Message.getFieldWithDefault(msg, 2, ""),
    privatekey: jspb.Message.getFieldWithDefault(msg, 3, ""),
    publickey: jspb.Message.getFieldWithDefault(msg, 4, ""),
    mnemonic: (f = msg.getMnemonic()) && proto.yeying.api.web3.Mnemonic.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yeying.api.web3.BlockAddress}
 */
proto.yeying.api.web3.BlockAddress.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yeying.api.web3.BlockAddress;
  return proto.yeying.api.web3.BlockAddress.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yeying.api.web3.BlockAddress} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yeying.api.web3.BlockAddress}
 */
proto.yeying.api.web3.BlockAddress.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setIdentifier(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddress(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPrivatekey(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPublickey(value);
      break;
    case 5:
      var value = new proto.yeying.api.web3.Mnemonic;
      reader.readMessage(value,proto.yeying.api.web3.Mnemonic.deserializeBinaryFromReader);
      msg.setMnemonic(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yeying.api.web3.BlockAddress.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yeying.api.web3.BlockAddress.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yeying.api.web3.BlockAddress} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yeying.api.web3.BlockAddress.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdentifier();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAddress();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPrivatekey();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPublickey();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMnemonic();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.yeying.api.web3.Mnemonic.serializeBinaryToWriter
    );
  }
};


/**
 * optional string identifier = 1;
 * @return {string}
 */
proto.yeying.api.web3.BlockAddress.prototype.getIdentifier = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.BlockAddress} returns this
 */
proto.yeying.api.web3.BlockAddress.prototype.setIdentifier = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string address = 2;
 * @return {string}
 */
proto.yeying.api.web3.BlockAddress.prototype.getAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.BlockAddress} returns this
 */
proto.yeying.api.web3.BlockAddress.prototype.setAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string privateKey = 3;
 * @return {string}
 */
proto.yeying.api.web3.BlockAddress.prototype.getPrivatekey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.BlockAddress} returns this
 */
proto.yeying.api.web3.BlockAddress.prototype.setPrivatekey = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string publicKey = 4;
 * @return {string}
 */
proto.yeying.api.web3.BlockAddress.prototype.getPublickey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.BlockAddress} returns this
 */
proto.yeying.api.web3.BlockAddress.prototype.setPublickey = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional Mnemonic mnemonic = 5;
 * @return {?proto.yeying.api.web3.Mnemonic}
 */
proto.yeying.api.web3.BlockAddress.prototype.getMnemonic = function() {
  return /** @type{?proto.yeying.api.web3.Mnemonic} */ (
    jspb.Message.getWrapperField(this, proto.yeying.api.web3.Mnemonic, 5));
};


/**
 * @param {?proto.yeying.api.web3.Mnemonic|undefined} value
 * @return {!proto.yeying.api.web3.BlockAddress} returns this
*/
proto.yeying.api.web3.BlockAddress.prototype.setMnemonic = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yeying.api.web3.BlockAddress} returns this
 */
proto.yeying.api.web3.BlockAddress.prototype.clearMnemonic = function() {
  return this.setMnemonic(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yeying.api.web3.BlockAddress.prototype.hasMnemonic = function() {
  return jspb.Message.getField(this, 5) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yeying.api.web3.Mnemonic.prototype.toObject = function(opt_includeInstance) {
  return proto.yeying.api.web3.Mnemonic.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yeying.api.web3.Mnemonic} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yeying.api.web3.Mnemonic.toObject = function(includeInstance, msg) {
  var f, obj = {
    phrase: jspb.Message.getFieldWithDefault(msg, 1, ""),
    path: jspb.Message.getFieldWithDefault(msg, 2, ""),
    locale: jspb.Message.getFieldWithDefault(msg, 3, ""),
    password: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yeying.api.web3.Mnemonic}
 */
proto.yeying.api.web3.Mnemonic.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yeying.api.web3.Mnemonic;
  return proto.yeying.api.web3.Mnemonic.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yeying.api.web3.Mnemonic} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yeying.api.web3.Mnemonic}
 */
proto.yeying.api.web3.Mnemonic.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhrase(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocale(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPassword(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yeying.api.web3.Mnemonic.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yeying.api.web3.Mnemonic.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yeying.api.web3.Mnemonic} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yeying.api.web3.Mnemonic.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPhrase();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLocale();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPassword();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string phrase = 1;
 * @return {string}
 */
proto.yeying.api.web3.Mnemonic.prototype.getPhrase = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.Mnemonic} returns this
 */
proto.yeying.api.web3.Mnemonic.prototype.setPhrase = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string path = 2;
 * @return {string}
 */
proto.yeying.api.web3.Mnemonic.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.Mnemonic} returns this
 */
proto.yeying.api.web3.Mnemonic.prototype.setPath = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string locale = 3;
 * @return {string}
 */
proto.yeying.api.web3.Mnemonic.prototype.getLocale = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.Mnemonic} returns this
 */
proto.yeying.api.web3.Mnemonic.prototype.setLocale = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string password = 4;
 * @return {string}
 */
proto.yeying.api.web3.Mnemonic.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.Mnemonic} returns this
 */
proto.yeying.api.web3.Mnemonic.prototype.setPassword = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yeying.api.web3.IdentityServiceExtend.prototype.toObject = function(opt_includeInstance) {
  return proto.yeying.api.web3.IdentityServiceExtend.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yeying.api.web3.IdentityServiceExtend} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yeying.api.web3.IdentityServiceExtend.toObject = function(includeInstance, msg) {
  var f, obj = {
    code: jspb.Message.getFieldWithDefault(msg, 1, ""),
    apis: jspb.Message.getFieldWithDefault(msg, 2, ""),
    proxy: jspb.Message.getFieldWithDefault(msg, 3, ""),
    grpc: jspb.Message.getFieldWithDefault(msg, 4, ""),
    extend: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yeying.api.web3.IdentityServiceExtend}
 */
proto.yeying.api.web3.IdentityServiceExtend.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yeying.api.web3.IdentityServiceExtend;
  return proto.yeying.api.web3.IdentityServiceExtend.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yeying.api.web3.IdentityServiceExtend} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yeying.api.web3.IdentityServiceExtend}
 */
proto.yeying.api.web3.IdentityServiceExtend.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setApis(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setProxy(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setGrpc(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setExtend(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yeying.api.web3.IdentityServiceExtend.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yeying.api.web3.IdentityServiceExtend.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yeying.api.web3.IdentityServiceExtend} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yeying.api.web3.IdentityServiceExtend.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCode();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getApis();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getProxy();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getGrpc();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getExtend();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string code = 1;
 * @return {string}
 */
proto.yeying.api.web3.IdentityServiceExtend.prototype.getCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.IdentityServiceExtend} returns this
 */
proto.yeying.api.web3.IdentityServiceExtend.prototype.setCode = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string apis = 2;
 * @return {string}
 */
proto.yeying.api.web3.IdentityServiceExtend.prototype.getApis = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.IdentityServiceExtend} returns this
 */
proto.yeying.api.web3.IdentityServiceExtend.prototype.setApis = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string proxy = 3;
 * @return {string}
 */
proto.yeying.api.web3.IdentityServiceExtend.prototype.getProxy = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.IdentityServiceExtend} returns this
 */
proto.yeying.api.web3.IdentityServiceExtend.prototype.setProxy = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string grpc = 4;
 * @return {string}
 */
proto.yeying.api.web3.IdentityServiceExtend.prototype.getGrpc = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.IdentityServiceExtend} returns this
 */
proto.yeying.api.web3.IdentityServiceExtend.prototype.setGrpc = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string extend = 5;
 * @return {string}
 */
proto.yeying.api.web3.IdentityServiceExtend.prototype.getExtend = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.IdentityServiceExtend} returns this
 */
proto.yeying.api.web3.IdentityServiceExtend.prototype.setExtend = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yeying.api.web3.IdentityOrganizationExtend.prototype.toObject = function(opt_includeInstance) {
  return proto.yeying.api.web3.IdentityOrganizationExtend.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yeying.api.web3.IdentityOrganizationExtend} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yeying.api.web3.IdentityOrganizationExtend.toObject = function(includeInstance, msg) {
  var f, obj = {
    address: jspb.Message.getFieldWithDefault(msg, 1, ""),
    code: jspb.Message.getFieldWithDefault(msg, 2, ""),
    extend: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yeying.api.web3.IdentityOrganizationExtend}
 */
proto.yeying.api.web3.IdentityOrganizationExtend.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yeying.api.web3.IdentityOrganizationExtend;
  return proto.yeying.api.web3.IdentityOrganizationExtend.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yeying.api.web3.IdentityOrganizationExtend} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yeying.api.web3.IdentityOrganizationExtend}
 */
proto.yeying.api.web3.IdentityOrganizationExtend.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddress(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setExtend(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yeying.api.web3.IdentityOrganizationExtend.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yeying.api.web3.IdentityOrganizationExtend.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yeying.api.web3.IdentityOrganizationExtend} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yeying.api.web3.IdentityOrganizationExtend.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddress();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCode();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getExtend();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string address = 1;
 * @return {string}
 */
proto.yeying.api.web3.IdentityOrganizationExtend.prototype.getAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.IdentityOrganizationExtend} returns this
 */
proto.yeying.api.web3.IdentityOrganizationExtend.prototype.setAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string code = 2;
 * @return {string}
 */
proto.yeying.api.web3.IdentityOrganizationExtend.prototype.getCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.IdentityOrganizationExtend} returns this
 */
proto.yeying.api.web3.IdentityOrganizationExtend.prototype.setCode = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string extend = 3;
 * @return {string}
 */
proto.yeying.api.web3.IdentityOrganizationExtend.prototype.getExtend = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.IdentityOrganizationExtend} returns this
 */
proto.yeying.api.web3.IdentityOrganizationExtend.prototype.setExtend = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yeying.api.web3.IdentityPersonalExtend.prototype.toObject = function(opt_includeInstance) {
  return proto.yeying.api.web3.IdentityPersonalExtend.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yeying.api.web3.IdentityPersonalExtend} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yeying.api.web3.IdentityPersonalExtend.toObject = function(includeInstance, msg) {
  var f, obj = {
    email: jspb.Message.getFieldWithDefault(msg, 1, ""),
    telephone: jspb.Message.getFieldWithDefault(msg, 2, ""),
    extend: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yeying.api.web3.IdentityPersonalExtend}
 */
proto.yeying.api.web3.IdentityPersonalExtend.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yeying.api.web3.IdentityPersonalExtend;
  return proto.yeying.api.web3.IdentityPersonalExtend.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yeying.api.web3.IdentityPersonalExtend} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yeying.api.web3.IdentityPersonalExtend}
 */
proto.yeying.api.web3.IdentityPersonalExtend.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTelephone(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setExtend(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yeying.api.web3.IdentityPersonalExtend.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yeying.api.web3.IdentityPersonalExtend.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yeying.api.web3.IdentityPersonalExtend} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yeying.api.web3.IdentityPersonalExtend.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTelephone();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getExtend();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string email = 1;
 * @return {string}
 */
proto.yeying.api.web3.IdentityPersonalExtend.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.IdentityPersonalExtend} returns this
 */
proto.yeying.api.web3.IdentityPersonalExtend.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string telephone = 2;
 * @return {string}
 */
proto.yeying.api.web3.IdentityPersonalExtend.prototype.getTelephone = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.IdentityPersonalExtend} returns this
 */
proto.yeying.api.web3.IdentityPersonalExtend.prototype.setTelephone = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string extend = 3;
 * @return {string}
 */
proto.yeying.api.web3.IdentityPersonalExtend.prototype.getExtend = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.IdentityPersonalExtend} returns this
 */
proto.yeying.api.web3.IdentityPersonalExtend.prototype.setExtend = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.yeying.api.web3.IdentityApplicationExtend.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yeying.api.web3.IdentityApplicationExtend.prototype.toObject = function(opt_includeInstance) {
  return proto.yeying.api.web3.IdentityApplicationExtend.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yeying.api.web3.IdentityApplicationExtend} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yeying.api.web3.IdentityApplicationExtend.toObject = function(includeInstance, msg) {
  var f, obj = {
    code: jspb.Message.getFieldWithDefault(msg, 1, ""),
    servicecodesList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    location: jspb.Message.getFieldWithDefault(msg, 3, ""),
    hash: jspb.Message.getFieldWithDefault(msg, 4, ""),
    extend: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yeying.api.web3.IdentityApplicationExtend}
 */
proto.yeying.api.web3.IdentityApplicationExtend.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yeying.api.web3.IdentityApplicationExtend;
  return proto.yeying.api.web3.IdentityApplicationExtend.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yeying.api.web3.IdentityApplicationExtend} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yeying.api.web3.IdentityApplicationExtend}
 */
proto.yeying.api.web3.IdentityApplicationExtend.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addServicecodes(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocation(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setHash(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setExtend(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yeying.api.web3.IdentityApplicationExtend.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yeying.api.web3.IdentityApplicationExtend.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yeying.api.web3.IdentityApplicationExtend} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yeying.api.web3.IdentityApplicationExtend.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCode();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getServicecodesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getLocation();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getHash();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getExtend();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string code = 1;
 * @return {string}
 */
proto.yeying.api.web3.IdentityApplicationExtend.prototype.getCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.IdentityApplicationExtend} returns this
 */
proto.yeying.api.web3.IdentityApplicationExtend.prototype.setCode = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated string serviceCodes = 2;
 * @return {!Array<string>}
 */
proto.yeying.api.web3.IdentityApplicationExtend.prototype.getServicecodesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.yeying.api.web3.IdentityApplicationExtend} returns this
 */
proto.yeying.api.web3.IdentityApplicationExtend.prototype.setServicecodesList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.yeying.api.web3.IdentityApplicationExtend} returns this
 */
proto.yeying.api.web3.IdentityApplicationExtend.prototype.addServicecodes = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.yeying.api.web3.IdentityApplicationExtend} returns this
 */
proto.yeying.api.web3.IdentityApplicationExtend.prototype.clearServicecodesList = function() {
  return this.setServicecodesList([]);
};


/**
 * optional string location = 3;
 * @return {string}
 */
proto.yeying.api.web3.IdentityApplicationExtend.prototype.getLocation = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.IdentityApplicationExtend} returns this
 */
proto.yeying.api.web3.IdentityApplicationExtend.prototype.setLocation = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string hash = 4;
 * @return {string}
 */
proto.yeying.api.web3.IdentityApplicationExtend.prototype.getHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.IdentityApplicationExtend} returns this
 */
proto.yeying.api.web3.IdentityApplicationExtend.prototype.setHash = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string extend = 5;
 * @return {string}
 */
proto.yeying.api.web3.IdentityApplicationExtend.prototype.getExtend = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.IdentityApplicationExtend} returns this
 */
proto.yeying.api.web3.IdentityApplicationExtend.prototype.setExtend = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yeying.api.web3.SecurityConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.yeying.api.web3.SecurityConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yeying.api.web3.SecurityConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yeying.api.web3.SecurityConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    algorithm: (f = msg.getAlgorithm()) && proto.yeying.api.web3.SecurityAlgorithm.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yeying.api.web3.SecurityConfig}
 */
proto.yeying.api.web3.SecurityConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yeying.api.web3.SecurityConfig;
  return proto.yeying.api.web3.SecurityConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yeying.api.web3.SecurityConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yeying.api.web3.SecurityConfig}
 */
proto.yeying.api.web3.SecurityConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.yeying.api.web3.SecurityAlgorithm;
      reader.readMessage(value,proto.yeying.api.web3.SecurityAlgorithm.deserializeBinaryFromReader);
      msg.setAlgorithm(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yeying.api.web3.SecurityConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yeying.api.web3.SecurityConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yeying.api.web3.SecurityConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yeying.api.web3.SecurityConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAlgorithm();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.yeying.api.web3.SecurityAlgorithm.serializeBinaryToWriter
    );
  }
};


/**
 * optional SecurityAlgorithm algorithm = 1;
 * @return {?proto.yeying.api.web3.SecurityAlgorithm}
 */
proto.yeying.api.web3.SecurityConfig.prototype.getAlgorithm = function() {
  return /** @type{?proto.yeying.api.web3.SecurityAlgorithm} */ (
    jspb.Message.getWrapperField(this, proto.yeying.api.web3.SecurityAlgorithm, 1));
};


/**
 * @param {?proto.yeying.api.web3.SecurityAlgorithm|undefined} value
 * @return {!proto.yeying.api.web3.SecurityConfig} returns this
*/
proto.yeying.api.web3.SecurityConfig.prototype.setAlgorithm = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yeying.api.web3.SecurityConfig} returns this
 */
proto.yeying.api.web3.SecurityConfig.prototype.clearAlgorithm = function() {
  return this.setAlgorithm(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yeying.api.web3.SecurityConfig.prototype.hasAlgorithm = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yeying.api.web3.SecurityAlgorithm.prototype.toObject = function(opt_includeInstance) {
  return proto.yeying.api.web3.SecurityAlgorithm.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yeying.api.web3.SecurityAlgorithm} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yeying.api.web3.SecurityAlgorithm.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    iv: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yeying.api.web3.SecurityAlgorithm}
 */
proto.yeying.api.web3.SecurityAlgorithm.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yeying.api.web3.SecurityAlgorithm;
  return proto.yeying.api.web3.SecurityAlgorithm.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yeying.api.web3.SecurityAlgorithm} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yeying.api.web3.SecurityAlgorithm}
 */
proto.yeying.api.web3.SecurityAlgorithm.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setIv(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yeying.api.web3.SecurityAlgorithm.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yeying.api.web3.SecurityAlgorithm.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yeying.api.web3.SecurityAlgorithm} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yeying.api.web3.SecurityAlgorithm.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getIv();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.yeying.api.web3.SecurityAlgorithm.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.SecurityAlgorithm} returns this
 */
proto.yeying.api.web3.SecurityAlgorithm.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string iv = 2;
 * @return {string}
 */
proto.yeying.api.web3.SecurityAlgorithm.prototype.getIv = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.yeying.api.web3.SecurityAlgorithm} returns this
 */
proto.yeying.api.web3.SecurityAlgorithm.prototype.setIv = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.yeying.api.web3.IdentityCodeEnum = {
  IDENTITY_CODE_UNKNOWN: 0,
  IDENTITY_CODE_PERSONAL: 1,
  IDENTITY_CODE_ORGANIZATION: 2,
  IDENTITY_CODE_SERVICE: 3,
  IDENTITY_CODE_APPLICATION: 4,
  IDENTITY_CODE_ASSET: 5
};

/**
 * @enum {number}
 */
proto.yeying.api.web3.NetworkTypeEnum = {
  NETWORK_TYPE_UNKNOWN: 0,
  NETWORK_TYPE_YEYING: 2020
};

goog.object.extend(exports, proto.yeying.api.web3);
